//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.CodeDom.Compiler;
using System.Configuration;
using System.Diagnostics;
using System.Drawing;
using System.Runtime.CompilerServices;

namespace GenshinAutoE.Properties
{


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
    {

        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default
        {
            get
            {
                return defaultInstance;
            }
        }

        [UserScopedSetting]
        [DebuggerNonUserCode]
        [DefaultSettingValue("0, 0")]
        public Point EAreaLocation
        {
            get
            {
                return (Point)this["EAreaLocation"];
            }
            set
            {
                this["EAreaLocation"] = value;
            }
        }
        [UserScopedSetting]
        [DebuggerNonUserCode]
        [DefaultSettingValue("0.6")]
        public float cmpMaxValue
        {
            get
            {
                return (float)this["cmpMaxValue"];
            }
            set
            {
                this["cmpMaxValue"] = value;
            }
        }
        [UserScopedSetting]
        [DebuggerNonUserCode]
        [DefaultSettingValue("0.1")]
        public float EPushTime
        {
            get
            {
                return (float)this["EPushTime"];
            }
            set
            {
                this["EPushTime"] = value;
            }
        }
        [UserScopedSetting]
        [DebuggerNonUserCode]
        [DefaultSettingValue("30")]
        public int captureFreshTime
        {
            get
            {
                return (int)this["captureFreshTime"];
            }
            set
            {
                this["captureFreshTime"] = value;
            }
        }
    }
}
